"""empty message

Revision ID: 3e86c4cec6f6
Revises: 858a90ae31be
Create Date: 2023-07-15 15:19:55.712018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e86c4cec6f6'
down_revision = '858a90ae31be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miles', sa.Float(), nullable=True))

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.alter_column('miles_current',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('miles_starting',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('miles_limit',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.alter_column('miles_limit',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('miles_starting',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('miles_current',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.drop_column('miles')

    # ### end Alembic commands ###
