"""empty message

Revision ID: 858a90ae31be
Revises: 0502f7721d65
Create Date: 2023-07-15 15:11:00.313342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858a90ae31be'
down_revision = '0502f7721d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miles_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('miles_starting', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('miles_limit', sa.Integer(), nullable=True))
        batch_op.drop_column('mile_limit')
        batch_op.drop_column('hours')
        batch_op.drop_column('miles')
        batch_op.drop_column('hour_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour_limit', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('miles', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hours', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mile_limit', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('miles_limit')
        batch_op.drop_column('miles_starting')
        batch_op.drop_column('miles_current')

    # ### end Alembic commands ###
