"""empty message

Revision ID: fa76c11c4fdb
Revises: 3e86c4cec6f6
Create Date: 2023-07-15 17:21:41.068077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa76c11c4fdb'
down_revision = '3e86c4cec6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('refresh_token_expiration',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('refresh_token_expiration',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
